spring:
  application:
    name: integration-api
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        hubspot:
          client-id: 0c482b5d-9a67-4059-a5b4-453403bfb32e
          client-secret: 136eb679-59b1-4870-8016-7f8d158d8864
          scope: crm.objects.contacts.read,crm.objects.contacts.write,oauth
          redirect-uri: http://localhost:8080/auth/hubspot/v1/token-exchange
          authorization-grant-type: authorization_code
          authorization-uri: https://app.hubspot.com/oauth/authorize
          token-uri: https://api.hubapi.com/oauth/v1/token
          introspect-token-uri: https://api.hubapi.com/oauth/v1/access-tokens
          introspect-refresh-token-uri: https://api.hubapi.com/oauth/v1/refresh-tokens

clients:
  hubspot:
    contact:
      uri: https://api.hubapi.com/crm/v3/objects/contacts